#' @title Summarize bandings
#' @description Counts the number of bird banded by year
#' @param df PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname summarize_bandings
#' @export
summarize_bandings <- function(df) {
  res = df %>%
    group_by(b.year) %>%
    summarise(n_banded = sum(count_of_birds))
  return(res)
}

#' @title Summarize recoveries
#' @description Count the number of recoveries by year
#' @param df PARAM_DESCRIPTION
#' @param by_band PARAM_DESCRIPTION, Default: FALSE
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname summarize_recoveries
#' @export
summarize_recoveries <- function(df, by_band = FALSE) {
  by_groups <- (if (by_band) {
    c("b.year", "add_info")
  } else {
    c("age_short", "b.year", "r.corrected_year")
  })
  res <- df %>% filter(b.year == r.corrected_year) %>%
    group_by_at(by_groups) %>%
    summarise(n_recoveries = n())
  return(res)
}

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param banding_df PARAM_DESCRIPTION
#' @param recoveries_df PARAM_DESCRIPTION
#' @param filters PARAM_DESCRIPTION, Default: NULL
#' @param banding_filters PARAM_DESCRIPTION, Default: NULL
#' @param recoveries_filters PARAM_DESCRIPTION, Default: NULL
#' @param filtered PARAM_DESCRIPTION, Default: FALSE
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname get_direct_recoveries
#' @export
get_direct_recoveries <-
  function(banding_df,
           recoveries_df,
           filters = NULL,
           banding_filters = NULL,
           recoveries_filters = NULL,
           filtered=FALSE) {
    if (!filtered) {
      b_filters <-
        if (is.null(banding_filters))
          filters
      else
        banding_filters
      banding_db <-
        filter_database(db = banding_df,
                        filters = b_filters,
                        db_type = "b")
      r_filters <-
        if (is.null(recoveries_filters))
          filters
      else
        recoveries_filters
      rec_db <-
        filter_database(db = recoveries_df,
                        filters = filters,
                        db_type = "r")
      SPEC = b_filters$SPEC
    } else {
      banding_db <- banding_df
      rec_db <- recoveries_df
      SPEC = unique(banding_db$SPEC)
    }

    bandings <- summarize_bandings(banding_db)
    recoveries <- summarize_recoveries(rec_db)

    dr_df <- merge(bandings, recoveries)

    dr_df <-
      dr_df %>% mutate(recov_rate = n_recoveries / n_banded) %>%
      mutate(var_recov_rate = (recov_rate * (1 - recov_rate)) / (n_banded - 1)) %>%
      mutate(se_recov_rate = sqrt(var_recov_rate))
    attr(dr_df, "SPEC") = SPEC
    return(dr_df)
  }

has_reporting_probas <- function(df) {
  return (all(c("rho", "var_rho") %in% colnames(df)))
}

has_recovery_rate <- function(df) {
  return (all(c("recov_rate", "var_recov_rate") %in% colnames(df)))
}

get_reporting_probabilities <- function(df, rho_df) {
  if (!has_reporting_probas(df)) {
    if (is.null(rho_df)) {
      rho_df = gb_reporting_probas
    }
    df <- inner_join(df, rho_df, by = "b.year")
  }
  return (df)
}


#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param df PARAM_DESCRIPTION, Default: NULL
#' @param rho_df PARAM_DESCRIPTION, Default: NULL
#' @param ... PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname get_harvest_rate
#' @export
get_harvest_rate <-
  function(df = NULL,
           rho_df = NULL,
           ...) {
    hr_df <- if (is.null(df)) {
      get_direct_recoveries(...)
    } else {
      if (!has_recovery_rate(df)) {
        stop(
          paste(
            "Missing columns for df argument. Please make sure the dataframe",
            "has been generated by the get_direct_recoveries() function"
          )
        )
      }
      df
    }
    hr_df <- get_reporting_probabilities(hr_df, rho_df)

    hr_df <- hr_df %>%
      mutate(harv_rate = recov_rate / rho) %>%
      mutate(var_harv_rate = (var_recov_rate / (rho ^ 2)) + ((recov_rate ^ 2 * var_rho) / rho ^ 4)) %>%
      mutate(se_harv_rate = sqrt(var_harv_rate)) %>%
      mutate(cl_harv_rate = se_harv_rate * 1.96) %>%
      mutate(cv_harv_rate = se_harv_rate / harv_rate)
    return(hr_df)
  }



get_confidence_levels <- function(df) {
  return(as.data.frame(cbind(
    b.year = df$b.year,
    start = (df$h - df$cl_h),
    end = (df$h + df$cl_h)
  )))
}

get_comparison_dataframe <-
  function(df = NULL,
           filters = NULL,
           pos = 1,
           ...) {
    if (is.null(df)) {
      if (is.null(filters)) {
        stop(sprintf(
          paste(
            "Dataframe to compare is missing. You must either",
            "provide a filtered data frame with the `df%s` argument or a",
            "list of filters with the `filters%s` argument."
          ),
          pos,
          pos
        ))
      }
      df <- get_harvest_rate(filters = filters, ...)
      if ("filter_name" %in% names(filters)) {
        df["type"] <- filters$filter_name
      }
    }
    if (!"type" %in% colnames(df)) {
      df["type"] = paste0("filters", pos)
    }
    return(df)
  }

#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param df1 PARAM_DESCRIPTION, Default: NULL
#' @param df2 PARAM_DESCRIPTION, Default: NULL
#' @param filters1 PARAM_DESCRIPTION, Default: NULL
#' @param filters2 PARAM_DESCRIPTION, Default: NULL
#' @param plot PARAM_DESCRIPTION, Default: TRUE
#' @param check_overlap PARAM_DESCRIPTION, Default: TRUE
#' @param ... PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname compare_harvest_rates
#' @export
compare_harvest_rates <-
  function(df1 = NULL,
           df2 = NULL,
           filters1 = NULL,
           filters2 = NULL,
           plot = TRUE,
           check_overlap = TRUE,
           ...) {
    # All Bands
    df1 <- get_comparison_dataframe(df1, filters1, 1, ...)
    df2 <- get_comparison_dataframe(df2, filters2, 2, ...)

    if (plot) {
      library(ggplot2)
      df <- rbind(df1, df2)
      both_plot <-
        ggplot(data = df, aes(x = b.year, y = harv_rate)) +
        geom_point(aes(color = type)) +
        geom_errorbar(aes(
          ymin = harv_rate - cl_harv_rate,
          ymax = harv_rate + cl_harv_rate
        ))
      print(both_plot)
    }

    if (check_overlap) {
      ## Compute overlap
      common_years <- intersect(df1$b.year, df2$b.year)

      # Get confidence levels
      cl1 <-
        get_confidence_levels(df1[df1$b.year %in% common_years, ])
      cl2 <-
        get_confidence_levels(df2[df2$b.year %in% common_years, ])
      # Check if there is an overlap
      overlap <-
        (cl2$start <= cl1$end) &
        (cl2$end >= cl1$start)
      # Return TRUE if all confidence levels overlap
      return(all(overlap))
    }
  }


#' @title FUNCTION_TITLE
#' @description FUNCTION_DESCRIPTION
#' @param df PARAM_DESCRIPTION, Default: NULL
#' @param harvest_df PARAM_DESCRIPTION, Default: NULL
#' @param harvest_correction_factor PARAM_DESCRIPTION, Default: 0.61
#' @param plot_estimates PARAM_DESCRIPTION, Default: TRUE
#' @param save_estimates PARAM_DESCRIPTION, Default: TRUE
#' @param save_path PARAM_DESCRIPTION, Default: '.'
#' @param ... PARAM_DESCRIPTION
#' @return OUTPUT_DESCRIPTION
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'  #EXAMPLE1
#'  }
#' }
#' @rdname get_lincoln_estimates
#' @export
get_lincoln_estimates <-
  function(df = NULL,
           harvest_df = NULL,
           harvest_correction_factor = 0.61,
           plot_estimates = TRUE,
           save_estimates = TRUE,
           save_path = ".",
           ...) {
    if (is.null(df)) {
      df <- get_harvest_rate(...)
    }
    if (is.null(harvest_df)) {
      # Should be an error since it is a big portion of estimates
      stop("A harvest dataframe for the selected species should be provided")
    }
    lincoln_df <- inner_join(df, harvest_df, by = "b.year")
    lincoln <- lincoln_df %>%
      mutate(harvest_adj = harvest * harvest_correction_factor) %>%
      mutate(se_harvest_adj = se_harvest * harvest_correction_factor) %>%
      mutate(var_harvest_adj = se_harvest_adj ^ 2) %>%
      mutate(N = ((((n_banded + 1) * (harvest_adj + 1) * rho
      ) / (n_recoveries + 1)) - 1)) %>%
      mutate(var_N_b.r = ((n_banded + 1) * (n_banded - n_recoveries)) / (((n_recoveries +
                                                                             1) ^ 2) * (n_recoveries + 2))) %>%
      mutate(var_N_bH.r =  ((n_banded / n_recoveries) ^ 2) * var_harvest_adj + harvest_adj ^
               2 * var_N_b.r) %>%
      mutate(var_N = (((
        n_banded * harvest_adj
      ) / n_recoveries) ^ 2) * var_rho + rho ^
        2 * var_N_bH.r) %>%
      mutate(se_N = sqrt(var_N)) %>%
      mutate(cl_N = se_N * 1.96)


    if (plot_estimates) {
      library(ggplot2)
      plt <- ggplot(data = lincoln, aes(x = b.year, y = N)) +
        geom_point() + geom_smooth() +
        scale_y_continuous(name = "Abundance (Lincoln)", limits = c(0, 500000)) +
        geom_errorbar(aes(ymin = N - cl_N, ymax = N + cl_N)) +
        labs(x = "Year")
      print(plt)
    }

    lincoln_est <-
      as.data.frame(cbind(lincoln$b.year, lincoln$N, lincoln$cl_N))
    colnames(lincoln_est) <- c("year", "N", "NCL")
    if (save_estimates) {
      print(attributes(df)$SPEC)
      SPEC <- if ("SPEC" %in% names(attributes(df))) {
        attributes(df)$SPEC
      } else {
        warning("Species was not found in the estimation dataframe. Please
                make sure df was created by the get_harvest_rate() function.
                Using 'UNKN' as species.")
        "UNKN"
      }
      file_path = file.path(save_path,
                            sprintf(
                              '%s_Lincoln_2000_2019_%s.csv',
                              SPEC,
                              format(Sys.time(), "%b%d_%Y")
                            ))
      write.csv(lincoln_est,
                file_path)
    }
    return(lincoln_est)

  }
